### ISSUE TITLE
Requirement for conda==4.5.12

### ISSUE THREAD

**Issue by stefanocorsi** [JRCSTU/co2wui#102]
```
Collecting conda==4.5.12 (from -r ./requirements.txt (line 28))
  ERROR: Could not find a version that satisfies the requirement conda==4.5.12 (from -r ./requirements.txt (line 28)) (from versions: 3.0.6, 3.5.0, 3.7.0, 3.17.0, 4.0.0, 4.0.1, 4.0.2, 4.0.3, 4.0.4, 4.0.5, 4.0.7, 4.0.8, 4.0.9, 4.1.2, 4.1.6, 4.2.6, 4.2.7, 4.3.13, 4.3.16)
ERROR: No matching distribution found for conda==4.5.12 (from -r ./requirements.txt (line 28))
```

**Comment by stefanocorsi** [comment]
Context:
pip install -r ./requirements.txt

**Comment by ankostis** [comment]
When i  re-generated requirements and probably forgote to run `bin/gen_reqs.txt` script i had made exactly for htis occasion.
And probably my environment was mistakenly a conda one (e.g `conda` is a conda-packahe not in *pypi*).

Check the diff of 7d7a7f63 to see the fixes needed and update the `bin/gen_reqs.txt` with a check that `CONDA_ENV_PATH` env-var is not set.

**Comment by stefanocorsi** [comment]
Ok, solved by:

- removing requirements for:
  - conda
  - menuinst
  from requirements.txt

Still a question: should those requirements be there for the conda packaging?! Or can we skip them?

**Comment by ankostis** [comment]
* `conda`, yes, it shoudl be.
* `menuinst`, no, it is needed for the conda-package, to install the start-menu items on Windows, but not for running the app.

**Comment by stefanocorsi** [comment]
Obsolete.
