### ISSUE TITLE
Problem with regex overriding "locale" and reading the locale dir as module

### ISSUE THREAD

**Issue by stefanocorsi** [JRCSTU/co2wui#104]

**Comment by stefanocorsi** [comment]
Regex.py (package regex) imports "locale" in a way that looks for the code in the current directory:

import regex._regex_core as _regex_core
import regex._regex as _regex
from threading import RLock as _RLock
**from locale import getpreferredencoding as _getpreferredencoding**
from regex._regex_core import *

Theres is a "locale" dir in the co2wui project, therefore the the import tries to read that one (wrong). Solution: rename dir or fix regex import.

**Comment by ankostis** [comment]
I would report it to [the *regex* project](https://pypi.org/project/regex/), but rename `locale` package into `i18n` which is actually a better to convey its purpose.
