### ISSUE TITLE
Enhancement of `Simulation summary`

### ISSUE THREAD

**Issue by dimitriskomnos** [JRCSTU/co2wui#108]
Here I list all the problems I see in the simulation summary: 

![image](https://user-images.githubusercontent.com/22169206/64779914-769b2800-d55f-11e9-91c0-792c9185ac3e.png)

and what to be fixed according to the picture above: 
- [ ] the NEDC High has two predictions, the one needs to go to the NEDC Low!! **See [1]**. 
- [ ] the CO2 values are the most important thing that can be shown in the table, please always put them on the top, no matter of the cycle (WLTP or NEDC, or whatever it is). **See [2]**.  
- [ ] Be consistent with what is printed. The NEDC High values are not there. **See [3]**.

**Comment by stefanocorsi** [comment]
See also https://github.com/JRCSTU/co2wui/issues/64
