### ISSUE TITLE
Add a download all button for the files to download

### ISSUE THREAD

**Issue by dimitriskomnos** [JRCSTU/co2wui#109]
Is it possible to add functionality to download all the files and/or select which ones to download?
For now it is not possible to run a whole folder, but if this is fixed, 
or if I run a file with lets say 100 simulation plans, 
then a list will appear like this: 
![image](https://user-images.githubusercontent.com/22169206/64783225-920a3100-d567-11e9-9144-c20f2706b480.png)

which is not very easy to work with, if for example you want to load stuff in python etc. 
And the path `C:\Users\user\.co2wui\output\` is kind of hidden.

**Comment by stefanocorsi** [comment]
Great one! Thanks.
