### ISSUE TITLE
Input template file not be saved in the Downloads automatically

### ISSUE THREAD

**Issue by dimitriskomnos** [JRCSTU/co2wui#111]
Same as the #110 

1. To be corrected so the user can choose where to save; 
2. it is very useful, important too, otherwise, we download several times same stuff

**Comment by stefanocorsi** [comment]
This is a browser related issue. It's the browser commanding how to deal with saved files. Firefox, for example, has an option that forces the browser to always ask the location when saving:

![immagine](https://user-images.githubusercontent.com/6546984/64854631-5ed6a900-d61e-11e9-999f-f6acc09be7dd.png)

In this way you can even specify the file name:

![immagine](https://user-images.githubusercontent.com/6546984/64854674-7c0b7780-d61e-11e9-9f88-6b3118d32539.png)

Would this solve the problem or do you think a more refined workaround should be taken?

In pratical terms we should point out to users that they can change the option if they want to be able to choose the destination folder for downloads.

In Chrome you have it here:

![immagine](https://user-images.githubusercontent.com/6546984/64854823-d4db1000-d61e-11e9-9838-8ba3386158d6.png)

For IE I have to do some more search.

**Comment by dimitriskomnos** [comment]
I think my set up is fine for chrome: 

![image](https://user-images.githubusercontent.com/22169206/64856270-e40f8d00-d621-11e9-9bbe-7077c5b0d2cc.png)

still, it gets downloaded in the Downloads.

**Comment by dimitriskomnos** [comment]
closing in favor of #112, 
and the material I put here I add there.
