### ISSUE TITLE
`Run simulation` & `Synchronize data` enhancement when choosing `options`

### ISSUE THREAD

**Issue by dimitriskomnos** [JRCSTU/co2wui#113]
It is generally working fine, but when following this procedure: 
1. without a selected file to synchronize uploaded going to the `options`
2. select an option for synchronization method
3. then select the file to sync

The sync menu of the options is disappearing, 
and he selected interpolation method is not saved, so it goes to the default

**Comment by stefanocorsi** [comment]
Good one. Thanks.
