### ISSUE TITLE
`Internal Server Error` message to be corrected from the following

### ISSUE THREAD

**Issue by dimitriskomnos** [JRCSTU/co2wui#114]
`Internal Server Error` message is popping out from the following: 

- [ ] CO2MPAS configuration when trying to download and delete
![image](https://user-images.githubusercontent.com/22169206/64791923-c5a18700-d578-11e9-9d02-f1b38b486024.png)

- [ ] `Load keys`, everywhere

**Comment by stefanocorsi** [comment]
It's been solved in the upcoming release.

**Comment by ankostis** [comment]
For the future, it would be nice to have cross-references, from the commit-message that fixed it.

**Comment by stefanocorsi** [comment]
@ankostis not pushed yet, the reference will be there.

**Comment by stefanocorsi** [comment]
8e0c630
