### ISSUE TITLE
co2wui from co2mpas dev1 exe, the dialog box with starter messages did not open

### ISSUE THREAD

**Issue by dimitriskomnos** [JRCSTU/co2wui#117]
Can someone confirm this? 

I think I did not see the dialog box popping out when I first opened the co2wui.

**Comment by stefanocorsi** [comment]
Have you tried with an anonymous browser? When you've checked the checkbox one for not getting anymore notifications a cookie is kept in your browser.

**Comment by dimitriskomnos** [comment]
Thanks for the hint!
I am sorry I think it works fine!
![image](https://user-images.githubusercontent.com/22169206/64856861-4f0d9380-d623-11e9-88d3-f34c0191cb0b.png)


Closing the issue
