### ISSUE TITLE
co2mpas run tab

### ISSUE THREAD

**Issue by gfon** [JRCSTU/co2wui#121]
Hi I realized that I miss elements here

*what happens if I want to run a batch simulation? I am not allowed to select multiple files **EDIT: i realised that I can single click individual vehicles and add them, but what happens if I have 50? (which is really the case)**
*the use declaration mode - engineering mode is not an advanced setting, better have it outside and visible
*the other options are rather cryptic, could we hyperlink them to the respective documentation to be prepared (not sure if I can add link here  tot the issue I opened in the other repo for @spycon69 @sapofra)

![image](https://user-images.githubusercontent.com/9556847/64863779-f693c180-d635-11e9-831b-3d2004b49765.png)

**Comment by stefanocorsi** [comment]
@gfon thanks, I answer first regarding the **cryptic options**. There's a built-in functionality (now removed) for contextual help. So we could for example have some "question marks" beside the options to explain what each options is. The best way to clarify something is in fact a short explanation text beside the thing to be explained.

**Comment by stefanocorsi** [comment]
@gfon regarding the multiple files, there's already a proposal from @dimitriskomnos for having the possibility to specify a directory as a source of input. https://github.com/JRCSTU/co2wui/issues/93

Another possibility, that I consider more "web oriented" would be to have a **multiple select file upload**.

In fact _raw_ selection of a directory path is not allowed by the browser and in general is a behaviour that is much in contrast with the way web application usually work (the application is not allowed to "touch" the file system). 

Instead a **multiple file upload** (maybe with a progress bar indicator and a drag and drop functionality) would probably be both friendly and functional.

**Comment by stefanocorsi** [comment]
@gfon see this as an example. Try to drag and drop some jpgs on the page and then you can start the global upload and get a very user friendly progress indicator:

http://www.markupdrive.com/demo/multiple-drag-and-drop-file-upload-jquery-plugin/

![immagine](https://user-images.githubusercontent.com/6546984/65078990-84590f00-d99e-11e9-8f17-a9aa00983c98.png)

**Comment by gfon** [comment]
@stefanocorsi thanks 
Please proceed with whatever option you think is best as long as we can add multiple files (the snapshot above looks nice)

-also fine about the question marks as long as there is some info about the options

**Comment by stefanocorsi** [comment]
I added commit d165f9b for the tooltips. To close this issue I need some help for the short texts to use for the contextual help.

![immagine](https://user-images.githubusercontent.com/6546984/65337807-2fe5a780-dbc9-11e9-9ce2-8c8cf43ca1c3.png)

- Use only declaration mode
- Hard validation
- Enable selector
- Only summary
