### ISSUE TITLE
input template and demo file

### ISSUE THREAD

**Issue by sapofra** [JRCSTU/co2wui#122]
I have noticed that if I download the input template (run) I get a dedicated page with the button to download, but if I download the demo file they are directly downloaded. 
I believe that these two actions should have the same behavior since they are the same, shouldn't they?

**Comment by stefanocorsi** [comment]
Yes, Francesca, what you say is correct. I'll have an intermediate page also for the demo file, it's better to actually click on a "download" button that simply clicking on a link and starting a download with no prompts.
