### ISSUE TITLE
Contact us page / Report a bug

### ISSUE THREAD

**Issue by spycon69** [JRCSTU/co2wui#42]
The contact us page has as a heading: Report a bug

Also email is mentioned twice both in the text and the link below

![contact_us](https://user-images.githubusercontent.com/38694686/60822856-8cc6e980-a1a6-11e9-8f93-37f39fb915eb.JPG)

**Comment by stefanocorsi** [comment]
I add the comment from GF: _about contact us, please eliminate twiter and phone (we don't have twitter or a phoneline), but you could add the link to git hub bug tracking page._
