### ISSUE TITLE
Move co2mpas FAQs under public co2mpas repository

### ISSUE THREAD

**Issue by stefanocorsi** [JRCSTU/co2wui#43]
At the moment the FAQs are in a personal repository, they should be moved under the public co2mpas one.

**Comment by stefanocorsi** [comment]
@dimitriskomnos ping

**Comment by dimitriskomnos** [comment]
Hi, 

I have added the F.A.Q in the public repository of CO2MPAS (CO2MPAS-TA), 
here: 
https://github.com/JRCSTU/CO2MPAS-TA/wiki/F-A-Q

Actions to follow: 
1. Change the link for the F.A.Q in the co2wui;
1. Add more stuff related to DICE and latest frequent questions we receive
