### ISSUE TITLE
Co2mpas testing semaphor

### ISSUE THREAD

**Issue by stefanocorsi** [JRCSTU/co2wui#46]
Please leave a comment below:

Start testing
Done testing

while your're testing Co2mpas GUI.

**Comment by stefanocorsi** [comment]
Please leave a comment:

Starting test
Done testing

while your're testing Co2mpas GUI.

**Comment by haphyp** [comment]
I'm testing it 16:50

Lorenzo

**Comment by haphyp** [comment]
Testing is over now 17:33

Lorenzo

**Comment by dimitriskomnos** [comment]
Started testing (locally)

**Comment by dimitriskomnos** [comment]
Started testing server as well

**Comment by sapofra** [comment]
Start testing h. 10.50

**Comment by ashenafimenza** [comment]
I started testing 10:52

**Comment by ashenafimenza** [comment]
started testing 11:56

**Comment by ashenafimenza** [comment]
Stopped testing 12:12

**Comment by sapofra** [comment]
Finished testing at 2.30 p.m
