### ISSUE TITLE
Adding a better waiting text in simulation 

### ISSUE THREAD

**Issue by haphyp** [JRCSTU/co2wui#47]
Since it takes a while (minutes) to produce an output in the Run Simulation page (http://217.61.126.82/run/progress?layout=layout&id=5816) maybe we should add the following text:
"Please wait for the process to complete, it may take up to 4 minutes to finish the process"

This to avoid that the user believes the system is in halt and not working.

![image](https://user-images.githubusercontent.com/21241609/60897303-230f1400-a268-11e9-9dd6-fcd208a622dc.png)

**Comment by stefanocorsi** [comment]
Totally true. We're designing a way together with Vincenzo to give the user feedback of any phase of the simulation.

**Comment by stefanocorsi** [comment]
Added progress bar and execution log.

![immagine](https://user-images.githubusercontent.com/6546984/62623071-36bda100-b920-11e9-9d06-8e11457ede44.png)
