### ISSUE TITLE
Link to F.A.Q not accessible if not logged in github

### ISSUE THREAD

**Issue by haphyp** [JRCSTU/co2wui#48]
This link: https://github.com/dimitriskomnos/co2mpas/wiki/CO2MPAS-F.A.Q.
is showing a 404 page if you are not logged in github.
![image](https://user-images.githubusercontent.com/21241609/60898587-6d44c500-a269-11e9-9394-e88fbd728639.png)

**Comment by stefanocorsi** [comment]
Thanks, it will be moved to a public repo.

**Comment by stefanocorsi** [comment]
I'm closing it because it will be solved with #43.
