### ISSUE TITLE
Status in view results page not clear

### ISSUE THREAD

**Issue by haphyp** [JRCSTU/co2wui#49]
![image](https://user-images.githubusercontent.com/21241609/60898795-b4cb5100-a269-11e9-979c-b47d86abbbe2.png)

This column in the http://217.61.126.82/run/view-results page is a bit confusing, OK and KO are too much similar. Maybe OK and ERROR would be better, or something similar..

**Comment by stefanocorsi** [comment]
Fixed, thanks.
