### ISSUE TITLE
Entire table is linked in page view result

### ISSUE THREAD

**Issue by haphyp** [JRCSTU/co2wui#50]
In page http://217.61.126.82/run/view-results if you rollover to this area: 
![image](https://user-images.githubusercontent.com/21241609/60899176-50f55800-a26a-11e9-986b-cfa57164a7a8.png)
the mouse reacts like he is hovering on a link. Only some sections are linked, like the Summary and the Log column. Maybe this link, that just reloads the page, can  be removed.
The same happens in other pages.  And on all website pages title and text (blue text).

**Comment by stefanocorsi** [comment]
Fixed. A broken link was enclosing the whole page.
