### ISSUE TITLE
selection in download data sync template not working

### ISSUE THREAD

**Issue by haphyp** [JRCSTU/co2wui#51]
Using Chrome, on the page http://217.61.126.82/sync/template-form

![image](https://user-images.githubusercontent.com/21241609/60899533-ebee3200-a26a-11e9-96c9-791870d73fdd.png)

the 2 selectors are not working.
Works in Explorer but not in Chrome and Firefox.

**Comment by stefanocorsi** [comment]
Fixed. The same old broken link was enclosing the page.
