### ISSUE TITLE
Load keys text description

### ISSUE THREAD

**Issue by spycon69** [JRCSTU/co2wui#56]
1. The sentence "For TA and TS use only" should be bold
2. The EU regulation should be completed or removed

![load_keys](https://user-images.githubusercontent.com/38694686/60977807-5f0dac00-a330-11e9-9679-a48ae1a6d2a7.JPG)

**Comment by stefanocorsi** [comment]
Thanks @spycon69. Do you or @sapofra know the exact reference to the regulation?
