### ISSUE TITLE
Main page icons

### ISSUE THREAD

**Issue by spycon69** [JRCSTU/co2wui#57]
The two icons should be placed to the right - aligned with the text description since the space as it is now looks congested
![main_page_icons](https://user-images.githubusercontent.com/38694686/60978333-418d1200-a331-11e9-8617-3c6f930f62b8.JPG)

**Comment by stefanocorsi** [comment]
@spycon69 I was thinking about that. What about instead leave them underneath but with a better spacing? 

![immagine](https://user-images.githubusercontent.com/6546984/60978733-e0b20980-a331-11e9-8217-d4f33327bd7f.png)

**Comment by spycon69** [comment]
Try with the centered alignment as well and then we decide

**Comment by stefanocorsi** [comment]
@spycon69 Could you sketch the suggested positioning? Is this what you mean?

![immagine](https://user-images.githubusercontent.com/6546984/61032505-da6b6e00-a3c1-11e9-84a3-03397a397e0e.png)

**Comment by stefanocorsi** [comment]
Reload page

**Comment by stefanocorsi** [comment]
![immagine](https://user-images.githubusercontent.com/6546984/61052575-fd127c80-a3eb-11e9-8e2e-2eaa77f05d18.png)

**Comment by spycon69** [comment]
I think the icons are not aligned 

![icon_alignment](https://user-images.githubusercontent.com/38694686/61057892-757e3b00-a3f6-11e9-9a97-bf8d315216e6.JPG)
