### ISSUE TITLE
Home page links + breadcrumbs

### ISSUE THREAD

**Issue by spycon69** [JRCSTU/co2wui#58]
Home page icon and breadcrumbs. At this moment, the co2mpas icon (car), the home icon and the Co2mpas breadcrumb all lead to the 1st page. I would suggest to remove the home icon and leave the remaining two links

![home_breadcrumbs](https://user-images.githubusercontent.com/38694686/60978623-b3fdf200-a331-11e9-98d3-6c4bad093bd9.JPG)

**Comment by stefanocorsi** [comment]
Thank you @spycon69 just a doubt about this: I'm just concerned that some users may have not so clear for themselves that clicking on the icon will bring them back to the home. Do you think the "home" link is confusing/disturbing?

**Comment by spycon69** [comment]
At this view we have 3 links to the Home Page which is an overkill. I suggested to remove the home button since I think that Co2mpas car icon should be present.
