### ISSUE TITLE
Run synchronisation

### ISSUE THREAD

**Issue by spycon69** [JRCSTU/co2wui#61]
The phrase "upload your data synchronisation input file"  should be omitted since it is already mentioned twice in the same page. 

In addition the "Start to load your input file by choosing an input file datasync file" has the word FILE mentioned twince and it might be a bit confusing since there is no such selection in this page.

![run_sync](https://user-images.githubusercontent.com/38694686/60979539-2fac6e80-a333-11e9-86bd-af4dc440d395.JPG)

**Comment by stefanocorsi** [comment]
Thank you @spycon69 of course, it was a typo.
