### ISSUE TITLE
Both NEDC High and WLTP High results are not visible in the `Simulation summary`

### ISSUE THREAD

**Issue by dimitriskomnos** [JRCSTU/co2wui#63]
The files we run have both High and Low data. 
While the Low results for the NEDC are printed, 
most of the High are not there!! 

![image](https://user-images.githubusercontent.com/22169206/61030627-100e5800-a3be-11e9-895f-82dd0bf11b6c.png)

**Comment by stefanocorsi** [comment]
@dimitriskomnos are you sure regardinf WLTP high? I see this:

![immagine](https://user-images.githubusercontent.com/6546984/61037913-4a7ef180-a3cc-11e9-833c-ca83ced4d85e.png)

**Comment by stefanocorsi** [comment]
Dovrebbe essere risolto adesso.
