### ISSUE TITLE
Typo&Texts

### ISSUE THREAD

**Issue by sapofra** [JRCSTU/co2wui#67]
![image](https://user-images.githubusercontent.com/29604134/61036720-ed823c00-a3c9-11e9-8932-8b3c1b9874cd.png)
 Joint Reserch Centre, C capital

**Comment by sapofra** [comment]
I think that the text allined as ![image](https://user-images.githubusercontent.com/29604134/61038307-135d1000-a3cd-11e9-9861-901eb21b7cdf.png) and not ![image](https://user-images.githubusercontent.com/29604134/61038323-1fe16880-a3cd-11e9-889e-a8c0529cbca8.png) are better looking.

**Comment by sapofra** [comment]
In the excel for the online tips, lots of words are in bold. They should be kept in bold because they correspond to the names of the buttons.

**Comment by stefanocorsi** [comment]
Thanks @sapofra I'll move your additions to a new issue, I prefer to have just "atomic" issues.
