### ISSUE TITLE
Menu 

### ISSUE THREAD

**Issue by sapofra** [JRCSTU/co2wui#68]
![image](https://user-images.githubusercontent.com/29604134/61037495-79e12e80-a3cb-11e9-8432-e6b4ff7f3266.png)
  or 
![image](https://user-images.githubusercontent.com/29604134/61037517-85345a00-a3cb-11e9-8f2b-a82c99406177.png)
  are much less confusing. Moreover, if I open one submenu the other closes, it is not possible to have all the sub-menus open.

**Comment by stefanocorsi** [comment]
What do you think about this combination?

![immagine](https://user-images.githubusercontent.com/6546984/61038325-2079ff00-a3cd-11e9-8fb4-5077a1e2711c.png)

**Comment by sapofra** [comment]
ok as well, but I would suggest increasing the font size of Home.

**Comment by stefanocorsi** [comment]
Done, please reload css.
