### ISSUE TITLE
co2wui test and report list

### ISSUE THREAD

**Issue by dimitriskomnos** [JRCSTU/co2wui#69]
### and if not open a new issue and edit the list below stating the number of the issue!

- Point browser to the home page. 
  1) Open the manual as indicated in the model dialog. **# check issue** #117 and report there 
  2) Close the dialog box  
  3) Reload the home page   
  4) Close the modal dialog box by checking the "do not show   anymore" checkbox   
  5) Reload the home page, check that modal dialog does not appear anymore   
  6) Check that all texts are complete 
  7) Check that texts make sense 
  8) Check that no grammar or spelling errors are present 
  9) Check that no visual incongruences are present 
  10) Check if shortcuts have been created in the Windows menu
- Check sidebar menu. 
  1) Check that all menu items are present
  2) Check that menu item are understandable
  3) Show model graph. **# check issue** #95
- Download a Co2mpas input template
  1) Check that the file is correct
  2) check that you can save in the desired path **# check issue** #111
- Click on Run simulation. 
  1) Check that all texts are complete
  2) Check that texts make sense
  3) Check that no grammar or spelling errors are present
  4) Check that no visual incongruences are present
  5) If an input file is present, please delete it
  6) Upload a Co2mpas 4.0 input file
  7) Delete the same file
  8) Upload it again
  9) Upload several ones
  10) Check that the "Start simulation" button is present
  11) Check the for "Stop simulation" button
  12) Start a simulation
  13) Check that the simulation terminates correctly
  14) Check result files
  15) Check summary file
  16) Check summary table (View summary)
  17) Check if the summary file values coincide with the View summary table **# check issue** #108
  18) Run a file with different "Advanced options", open the file each time and check if this is correct. 
- Back to Run simulation. Delete input file
  1) Upload a wrong input file (could be whatever xlsx file)
  2) Start a simulation
  3) Check that the simulation terminates with an error
- Go to view results. Check that the simulations done are present
  1) Check that the result codes are correct
  2) Check that the files are the correct ones
  3) Delete some result files
  4) Delete all result files
- Synchronization. 
  1) Check that all texts are complete
  2) Check that texts make sense
  3) Check that no grammar or spelling errors are present
  4) Check that no visual incongruences are present
  5) Download simulation template **# check issue** #112
  6) Check that the file is correct
  7) Fill the file with wrong data
  8) Run synchronization (you should get an error)
  9) Fill the file with correct data
  10) Run synchronization (you should get a positive result)
  11) Download synchronized file
  12) Check that the synchronized file is correct
  13) Use randomly 2 different options for interpolation and check if the results change 
  14) Use file as input data for a Co2mpas input file and run a simulation
- Click on Load keys. Check that all texts are complete
  1) Check that texts make sense
  2) Check that no grammar or spelling errors are present
  3) Check that no visual incongruences are present
  4) Delete all keys (if present) **# check issue** #76 probably not implemented
  5) Load wrong keys **# check issue** #76 probably not implemented
  6) Run co2mpas simulation in TA mode (you should get an error) 
  7) Load correct keys **# check issue** #76 proably not implemented
  8) Run co2mpas simulation in TA mode (you should get a  result)
- Click on Expert functionalities. Only for local installations!!! Show model graph
  1) A browser window should open with the Co2mpas model shown **# check issue** #95
  2) Click on Co2mpas configuration **# check issue** #114 #115
  3) Generate a blank Co2mpas configuration file
  4) Download generated config file **# check issue** #114
  5) Modify config file **# check issue** #114
  6) Upload modified config file
  7) Download uploaded config file and check that the changes are there
- Click on Demo file. 
  8) A zip file containing co2mpas demo should be downloaded
  9) Check that the contents are correct
- Other pages. 
  1) Check that all texts are complete for FAQ, Tutorials, Documentation: 
![image](https://user-images.githubusercontent.com/22169206/64799069-592c8500-d584-11e9-90d9-607f4a889f6e.png)
  2) Check that texts make sense
  3) Check that no grammar or spelling errors are present
  4) Check that no visual incongruences are present
  5) Propose changes

**Comment by VictorValverde** [comment]
I can comment
