### ISSUE TITLE
Delete modal pop-up

### ISSUE THREAD

**Issue by sapofra** [JRCSTU/co2wui#72]
the *Lorem ipsum* sentence is still present, should be deleted everywhere

**Comment by stefanocorsi** [comment]
Thanks @sapofra. Can you attach a screenshot?

**Comment by sapofra** [comment]
No sorry, I cannot. they are not captured in the screenshot

**Comment by stefanocorsi** [comment]
Are you referring to the news?

![immagine](https://user-images.githubusercontent.com/6546984/61050154-963e9480-a3e6-11e9-8d99-e5e77da7539f.png)

**Comment by sapofra** [comment]
no. for example, if you put your mouse above "Welcome to Co2mpas" you will see what I mean

**Comment by stefanocorsi** [comment]
Ahhh got it. Thanks!
