### ISSUE TITLE
Run simulation with a wrong input file

### ISSUE THREAD

**Issue by sapofra** [JRCSTU/co2wui#74]
![image](https://user-images.githubusercontent.com/29604134/61041004-f5de7500-a3d1-11e9-9426-9eb113940dae.png)
 Maybe a X instead of a flag would make more sense, since the result is negative.

**Comment by stefanocorsi** [comment]
Right you are. Thanks @sapofra

**Comment by stefanocorsi** [comment]
![immagine](https://user-images.githubusercontent.com/6546984/61059192-e6265700-a3f8-11e9-9eda-fc266d6d479a.png)
