### ISSUE TITLE
Changing browser or screen size

### ISSUE THREAD

**Issue by ashenafimenza** [JRCSTU/co2wui#75]
I dont know if this is really important but for curiosity I just checked opening on different mobile devices if the wui fits. The links on the topbar GitHub, DICE, FAQ and the search box disappears
for a resolution below 768 * 1137.
![mobile](https://user-images.githubusercontent.com/16180761/61042358-5d95bf80-a3d4-11e9-9418-7c7551eb980b.png)

**Comment by stefanocorsi** [comment]
Right you are. Thanks @ashenafimenza

**Comment by stefanocorsi** [comment]
![immagine](https://user-images.githubusercontent.com/6546984/65081714-8de57580-d9a4-11e9-8ceb-0c599ee696c3.png)
