### ISSUE TITLE
Messages in the log window to be fixed

### ISSUE THREAD

**Issue by dimitriskomnos** [JRCSTU/co2wui#77]
Right now the only thing that appears is: 
```Waiting for data...```

![image](https://user-images.githubusercontent.com/22169206/61048918-7fe30980-a3e3-11e9-8b7d-537b5d427773.png)

This is confusing. 
I think it is **more** than fine to print the logs as co2mpas does

**Comment by stefanocorsi** [comment]
@dimitriskomnos don't you get a three lines of log at the end? This issue is dependent on  #47

**Comment by stefanocorsi** [comment]
I close it because substantially analog to #47

**Comment by dimitriskomnos** [comment]
I am sorry, didn't see..
