### ISSUE TITLE
Run simulation missing stop button

### ISSUE THREAD

**Issue by sapofra** [JRCSTU/co2wui#79]
- [x] There is no button to stop the run

- [x] If I launch the simulation and meanwhile I do something else (download a demo file for example) the simulation stops.

**Comment by stefanocorsi** [comment]
Regarding2: 
The simulation does not stop, but it is not anymore visible in the simulation form. It's visible in the view results page.

**Comment by sapofra** [comment]
mmm, look this is what I get: 
![image](https://user-images.githubusercontent.com/29604134/61056610-f8ea5d00-a3f3-11e9-9bb6-db0165965a64.png) as you can see I have an error

**Comment by stefanocorsi** [comment]
Ok, we'll change the behaviour so that when going back to the rum simulation page the GUI will display the progress of the running simulation. Thx
