### ISSUE TITLE
Sync tool of the server does not change the input file

### ISSUE THREAD

**Issue by dimitriskomnos** [JRCSTU/co2wui#83]
I am testing the synchronization tool in the server.
I load different files, but they all give the same output. I do not know if it is a problem of the server today, or is always like this. 
Whatever file I run right now (either with different names), it gives me the same output. Please check this and let me know.

I have to point some stuff that need to be considered and currently I can not test: 
- What happens if I apply changes in a datasync input file, save it and run again? 
- Do I need to "upload" again the file? I guess that yes, bt please confirm and then we will need to write this in the instructions as note. 
- What happens if I do changes in a file and try to upload the file with the same name? Will it overwrite and keep the new file?

**Comment by stefanocorsi** [comment]
Cache problem, will be fixed by appending a timestr to the URL.
