### ISSUE TITLE
RFE: coalesce organize folders, not to pollute cwd

### ISSUE THREAD

**Issue by ankostis** [JRCSTU/co2wui#87]
- For uploaded keys, it's better to store them under user's home dir, inside `pathlib.Path.home() / ".co2wui"`.
- For the various IO-folder, currently (input, output, logs), it's better to group them also under a single folder - this parent frolder can be placed:
  -  inside `cwd`, 
  - inside `/tmp` (using `tmpfile` lib, 
  - or in the above aforementioned user-home folder.  

It's customary to report the location of those folders in the documentation.

**Comment by ankostis** [comment]
Any ideas?

**Comment by ankostis** [comment]
Actually it may be a bug, because if not run from within git-repo,
the `sync/` dir does not exist, and syncing does not work (#86).

**Comment by stefanocorsi** [comment]
Ok, I've followed your steps and created a co2wui_fpath function that always relocate the given arguments to user's HOME. Es. co2wui_fpath('sync', 'input', fname) woulbd be $HOME/.co2wui/sync/input/<fname>
