### ISSUE TITLE
Make an option to specify a whole folder with inputs to run

### ISSUE THREAD

**Issue by dimitriskomnos** [JRCSTU/co2wui#93]
It is very time-consuming to put one by one the input files to run. 
Please make an option to select a whole folder with input files (everything starting with .xlsx). 

This was an option for previous GUI, and it is permitted by the console (currenlty there is a bug though).

**Comment by spycon69** [comment]
Was this functionality defined in the initial requirements ?

**Comment by dimitriskomnos** [comment]
I see in clickup the document produced by Vins if I recall correctly, here: 
https://app.clickup.com/t/p899w
I do not know if there is something more. 
There is says only _`Run co2mpas (all modes)`_. 
Running a whole folder might was neglected to be specifically mentioned in the requirements, but for sure it is how co2mpas works, and it was an option in the previous GUI as well. 
I have already mentioned this to @stefanocorsi that it would be nice to have. 

In my opinion, it is not the most important thing, but:
- if there is time until the release, 
- if it is not so demanding and does not need a big re-structure, 
I propose to think of a way to implement: 
- Either an option to upload all the excel files in a folder;
- Or to be able when the window to select an input file opens, to permit you to select multiple ones.

**Comment by stefanocorsi** [comment]
See also: https://github.com/JRCSTU/co2wui/issues/121

**Comment by stefanocorsi** [comment]
This issue is temporarily solved by the multiple file upload functionality.
