### ISSUE TITLE
RFE: Don't re-launch backend-server if already running (auto-close?, etc) 

### ISSUE THREAD

**Issue by ankostis** [JRCSTU/co2wui#97]
REWORK launch command:

- [x] 1. Don't launch a new server on each `co2wui run` command.
- [x] 2. Either automaticaly close on exit or remind the user to close the backend server. 
- [ ] 3. Using a "less devolpment" werkzeug, like gevent, to support multi-threading.
- [ ] 4. Refactor command, not to launch browser for `--help` or other verbs.

**Comment by stefanocorsi** [comment]
Some things that come to my mind (there may be smarter solutions)...

- Check tcp port and see if server is active
- Create a lock file or something
- Keep track of the server in the process table

**Comment by ankostis** [comment]
For bullet (1) of OP, use the tcp-port;  many single-instance programs do that, and in our case, it comes for free (flask fails when trying to listen to the used port).

What to do next, after the port is taken, we have various options:
- Bind into another port, just to print an ugly message that 
  there is another window open - but what if it isn't? 
  What if user has closed it by mistake, and flask is still running in the background? 
  (depends on the solution for bullet (2))).
- re-open a new tab in the browser (nice if you accidentally have closed it all tabs to *co2wui*, confusing if you haven't);
- detect if there is another tab open, do act accordingly.

The last option is professional. 
But it's nice to solve them in tandem with [1] bullet.  For the later i can't think anything else but adding an icon in the notifications area[2] when *co2wui* server is running.

[1] https://stackoverflow.com/questions/23690666/check-if-my-website-is-open-in-another-tab
[2] https://stackoverflow.com/questions/9494739/how-to-build-a-systemtray-app-for-windows

**Comment by ankostis** [comment]
There are some bugs in 2e5e917 regarding bogus dependencies in `setup.py` for standard libs.  The general objective also needs work before closing this, e.g. the app is still launched from the `FlaskGroup` class.

**Comment by stefanocorsi** [comment]
@ankostis I think this issue is closed now, I'd like to get rid of issues as long as development proceeds, please let's open another issue if the current behaviour won't be satisfying in the next release.
