### ISSUE TITLE
datasync'ed files are always saved in the Downloads folder

### ISSUE THREAD

**Issue by dimitriskomnos** [JRCSTU/co2wui#98]
When I syncrhonize a file and then I press to download, 
there is no window opened to specify the path to save it, and automatically saves it in the `Downloads` folder. 
Although in my chrome I have selected the option to ask me where to save.

**Comment by dimitriskomnos** [comment]
Actually for the current dev: 

- if I open the co2wui from the console, the automatically creates in the current path the below folders: 
  - **./input** and **./output** for the simulation files; 
  - **./syn/input** and **./syn/output**
in this case the datasync.sync.xlsx is saved both in the **./syn/output** and in the Downloads. 
- if I open the co2wui from the start menu, the file is saved only in the Downloads. 

I will mention it here as well, please change the name of the output file!

**Comment by ankostis** [comment]
Probably result of my #91. 
I would mark this issue here as duplicate, and move it's opening-post as a comment in #87,
which should become the master bug to track the folders reorganization.

**Comment by stefanocorsi** [comment]
Could we summarize this together with #110, #111, #112 and keep only one open? Please let me know if they can be grouped. Thanks

**Comment by dimitriskomnos** [comment]
Closing in favor of #112
